if game.IsDedicated() then
    RunConsoleCommand( "jerminator_dynamic_content", 1 )

end

local jermaSpawnSet = {
    name = "jermas_glee", -- unique name
    prettyName = "Jerma's Glee",
    description = "Meet Jerma!",
    difficultyPerMin = "default", -- difficulty per minute
    waveInterval = "default", -- time between spawn waves
    diffBumpWhenWaveKilled = "default*0.5", -- when there's <= 1 hunter left, the difficulty is permanently bumped by this amount
    startingBudget = "default", -- so budget isnt 0
    spawnCountPerDifficulty = "default*0.35", -- max of ten at 10 minutes
    startingSpawnCount = "default*0.75",
    maxSpawnCount = "default",
    maxSpawnDist = "default",
    roundEndSound = "default",
    roundStartSound = "default",
    spawns = {
        {
            hardRandomChance = nil,
            name = "jerma_scared", -- unique name
            prettyName = "A Jerma",
            class = "terminator_nextbot_jerminator_scared", -- class spawned
            spawnType = "hunter",
            difficultyCost = { 1, 5 },
            countClass = "terminator_nextbot_jerminator*", -- class COUNTED
            minCount = 1,
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "jerma_normal",
            prettyName = "A Jerma",
            class = "terminator_nextbot_jerminator",
            spawnType = "hunter",
            difficultyCost = { 3, 6 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 5 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_985_rareearly",
            prettyName = "A Jerma985",
            class = "terminator_nextbot_jerminator_realistic",
            spawnType = "hunter",
            difficultyCost = { 15, 25 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "jerma_985_common",
            prettyName = "A Jerma985",
            class = "terminator_nextbot_jerminator_realistic",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 8 },
            difficultyNeeded = { 35, 80 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_98SIX_rareearly",
            prettyName = "A Jerma986",
            class = "terminator_nextbot_jerminatorwraith",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminatorwraith",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 20 },
            name = "jerma_98SIX_common",
            prettyName = "A Jerma986",
            class = "terminator_nextbot_jerminatorwraith",
            spawnType = "hunter",
            difficultyCost = { 70, 130 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 4 },
            difficultyNeeded = { 45, 100 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_98NINETYONE_rareearly",
            prettyName = "A Jerma991",
            class = "terminator_nextbot_jerminatorwizard",
            spawnType = "hunter",
            difficultyCost = { 25, 55 },
            countClass = "terminator_nextbot_jerminatorwizard",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 20 },
            name = "jerma_98NINETYONE_common",
            prettyName = "A Jerma991",
            class = "terminator_nextbot_jerminatorwizard",
            spawnType = "hunter",
            difficultyCost = { 70, 180 },
            countClass = "terminator_nextbot_jerminatorwizard",
            maxCount = { 4 },
            difficultyNeeded = { 50, 120 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_98SEVEN_rareearly",
            prettyName = "A Jerma987",
            class = "terminator_nextbot_jerminatorhuge",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminatorhuge",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 20 },
            name = "jerma_98SEVEN_common",
            prettyName = "A Jerma987",
            class = "terminator_nextbot_jerminatorhuge",
            spawnType = "hunter",
            difficultyCost = { 70, 180 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 10 },
            difficultyNeeded = { 50, 120 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_98EIGHT_rareearly",
            prettyName = "A Jerma988",
            class = "terminator_nextbot_jerminatorsmol",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminatorsmol",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 20 },
            name = "jerma_98EIGHT_common",
            prettyName = "A Jerma988",
            class = "terminator_nextbot_jerminatorsmol",
            spawnType = "hunter",
            difficultyCost = { 20, 40 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 15 },
            difficultyNeeded = { 30, 70 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_98NINE_rareearly",
            prettyName = "A Jerma989",
            class = "terminator_nextbot_jerminatorwide",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminatorwide",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 11, 23 },
            name = "jerma_98NINE_common",
            prettyName = "A Jerma989",
            class = "terminator_nextbot_jerminatorwide",
            spawnType = "hunter",
            difficultyCost = { 100, 210 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 10 },
            difficultyNeeded = { 60, 150 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.2, 1 },
            name = "jerma_99ZERO_rareearly",
            prettyName = "A Jerma990",
            class = "terminator_nextbot_jerminatorstronk",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            countClass = "terminator_nextbot_jerminatorstronk",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 20 },
            name = "jerma_99ZERO_common",
            prettyName = "A Jerma990",
            class = "terminator_nextbot_jerminatorstronk",
            spawnType = "hunter",
            difficultyCost = { 65, 185 },
            countClass = "terminator_nextbot_jerminator*",
            maxCount = { 3 },
            difficultyNeeded = { 55, 130 },
            postSpawnedFuncs = nil,
        },
    }
}

table.insert( GLEE_SPAWNSETS, jermaSpawnSet )
